### ISSUE TITLE
way to resize this? 

### ISSUE THREAD

**Issue by nholmvio** [janoschp/simple_speed_dial#3]
Hello...is there a way to resize this properly?  When i follow the normal FAB resizing advice (fitted box within container approach:
floatingActionButton: Container(
        height: 100.0,
        width: 100.0,
        child: FittedBox(
          child: FloatingActionButton(onPressed: () {}),
        ),
      ),
) the FAB resizes to be very small when i activate the speed dial...

are others able to resize this without issue?

**Comment by janoschp** [comment]
no, one size fits all
